export const workouts = [
  // CORE (1-10)
  { id: 1, name: 'Jumping Jacks', muscle: 'Core', category: 'Pre_warmup', level: 'Beginner', image: 'jumping_jacks' },
  { id: 2, name: 'Standing Side Bends', muscle: 'Core', category: 'Pre_warmup', level: 'Beginner', image: 'standing_side_bends' },
  { id: 3, name: 'Plank', muscle: 'Core', category: 'Bodyweight', level: 'Intermediate', image: 'plank' },
  { id: 4, name: 'Sit-up', muscle: 'Core', category: 'Bodyweight', level: 'Beginner', image: 'sit_up' },
  { id: 5, name: 'Ab Wheel Rollout', muscle: 'Abs', category: 'Equipment', level: 'Advanced', image: 'ab_wheel_rollout' },
  { id: 6, name: 'BOSU Ball Crunch', muscle: 'Core', category: 'Equipment', level: 'Intermediate', image: 'bosu_ball_crunch' },
  { id: 7, name: 'Cable Woodchoppers', muscle: 'Core', category: 'Cable', level: 'Intermediate', image: 'cable_woodchoppers' },
  { id: 8, name: 'Machine Crunch', muscle: 'Core', category: 'Machine', level: 'Beginner', image: 'machine_crunch' },
  { id: 9, name: 'Mountain Climbers', muscle: 'Core', category: 'Bodyweight', level: 'Intermediate', image: 'mountain_climbers' },
  { id: 10, name: 'Dead Bug', muscle: 'Core', category: 'Post_warmup', level: 'Beginner', image: 'dead_bug' },

  // SHOULDERS (11-20)
  { id: 11, name: 'Arm Circles', muscle: 'Shoulders', category: 'Pre_warmup', level: 'Beginner', image: 'arm_circles' },
  { id: 12, name: 'Shoulder Shrugs (No Weights)', muscle: 'Shoulders', category: 'Pre_warmup', level: 'Beginner', image: 'shoulder_shrugs_no_weights' },
  { id: 13, name: 'Overhead Press (Barbell)', muscle: 'Shoulders', category: 'Barbell', level: 'Intermediate', image: 'barbell_overhead_press' },
  { id: 14, name: 'Arnold Press', muscle: 'Shoulders', category: 'Dumbbell', level: 'Advanced', image: 'arnold_press' },
  { id: 15, name: 'Lateral Raise', muscle: 'Shoulders', category: 'Dumbbell', level: 'Beginner', image: 'lateral_raise' },
  { id: 16, name: 'Front Raise', muscle: 'Shoulders', category: 'Dumbbell', level: 'Beginner', image: 'front_raise' },
  { id: 17, name: 'Cable Lateral Raise', muscle: 'Shoulders', category: 'Cable', level: 'Intermediate', image: 'cable_lateral_raise' },
  { id: 18, name: 'Machine Shoulder Press', muscle: 'Shoulders', category: 'Machine', level: 'Beginner', image: 'machine_shoulder_press' },
  { id: 19, name: 'Shoulder Shrug (Barbell)', muscle: 'Shoulders', category: 'Barbell', level: 'Intermediate', image: 'barbell_shoulder_shrug' },
  { id: 20, name: 'Rear Delt Fly (Machine)', muscle: 'Shoulders', category: 'Post_warmup', level: 'Intermediate', image: 'rear_delt_fly_machine' },

  // CHEST (21-30)
  { id: 21, name: 'Arm Swings', muscle: 'Chest', category: 'Pre_warmup', level: 'Beginner', image: 'arm_swings' },
  { id: 22, name: 'Chest Opener Stretch', muscle: 'Chest', category: 'Pre_warmup', level: 'Beginner', image: 'chest_opener_stretch' },
  { id: 23, name: 'Push-ups', muscle: 'Chest', category: 'Bodyweight', level: 'Beginner', image: 'push_ups' },
  { id: 24, name: 'Barbell Bench Press', muscle: 'Chest', category: 'Barbell', level: 'Intermediate', image: 'barbell_bench_press' },
  { id: 25, name: 'Incline Dumbbell Bench Press', muscle: 'Chest', category: 'Dumbbell', level: 'Advanced', image: 'incline_dumbbell_bench_press' },
  { id: 26, name: 'Machine Chest Fly', muscle: 'Chest', category: 'Machine', level: 'Beginner', image: 'machine_chest_fly' },
  { id: 27, name: 'Cable Chest Fly', muscle: 'Chest', category: 'Cable', level: 'Intermediate', image: 'cable_chest_fly' },
  { id: 28, name: 'Decline Dumbbell Bench Press', muscle: 'Chest', category: 'Dumbbell', level: 'Advanced', image: 'decline_dumbbell_bench_press' },
  { id: 29, name: 'Chest Dips (Bodyweight)', muscle: 'Chest', category: 'Bodyweight', level: 'Intermediate', image: 'chest_dips' },
  { id: 30, name: 'Chest Stretch (Post)', muscle: 'Chest', category: 'Post_warmup', level: 'Beginner', image: 'chest_stretch_post' },

  // LEGS (31-40)
  { id: 31, name: 'High Knees', muscle: 'Legs', category: 'Pre_warmup', level: 'Beginner', image: 'high_knees' },
  { id: 32, name: 'Butt Kicks', muscle: 'Legs', category: 'Pre_warmup', level: 'Beginner', image: 'butt_kicks' },
  { id: 33, name: 'Barbell Squat', muscle: 'Legs', category: 'Barbell', level: 'Intermediate', image: 'barbell_squat' },
  { id: 34, name: 'Dumbbell Lunge', muscle: 'Legs', category: 'Dumbbell', level: 'Intermediate', image: 'dumbbell_lunge' },
  { id: 35, name: 'Leg Press (Machine)', muscle: 'Legs', category: 'Machine', level: 'Beginner', image: 'leg_press_machine' },
  { id: 36, name: 'Cable Pull-Through', muscle: 'Legs', category: 'Cable', level: 'Intermediate', image: 'cable_pull_through' },
  { id: 37, name: 'Bodyweight Squat', muscle: 'Legs', category: 'Bodyweight', level: 'Beginner', image: 'bodyweight_squat' },
  { id: 38, name: 'Machine Hack Squat', muscle: 'Legs', category: 'Machine', level: 'Intermediate', image: 'machine_hack_squat' },
  { id: 39, name: 'Dumbbell Step-Up', muscle: 'Legs', category: 'Dumbbell', level: 'Intermediate', image: 'dumbbell_step_up' },
  { id: 40, name: 'Quad Stretch (Post)', muscle: 'Legs', category: 'Post_warmup', level: 'Beginner', image: 'quad_stretch_post' },

  // BACK (41-50)
  { id: 41, name: 'Cat-Camel Stretch', muscle: 'Back', category: 'Pre_warmup', level: 'Beginner', image: 'cat_camel_stretch' },
  { id: 42, name: 'Bent Over T-Spine Rotation', muscle: 'Back', category: 'Pre_warmup', level: 'Beginner', image: 'bent_over_t_spine_rotation' },
  { id: 43, name: 'Deadlift (Barbell)', muscle: 'Back', category: 'Barbell', level: 'Intermediate', image: 'barbell_deadlift' },
  { id: 44, name: 'Bent Over Row (Barbell)', muscle: 'Back', category: 'Barbell', level: 'Intermediate', image: 'bent_over_row_barbell' },
  { id: 45, name: 'Pull-ups (Bodyweight)', muscle: 'Back', category: 'Bodyweight', level: 'Intermediate', image: 'pull_ups' },
  { id: 46, name: 'Chin-ups (Bodyweight)', muscle: 'Back', category: 'Bodyweight', level: 'Intermediate', image: 'chin_ups' },
  { id: 47, name: 'Cable Seated Row', muscle: 'Back', category: 'Cable', level: 'Intermediate', image: 'cable_seated_row' },
  { id: 48, name: 'Machine Lat Pulldown', muscle: 'Back', category: 'Machine', level: 'Beginner', image: 'machine_lat_pulldown' },
  { id: 49, name: 'Inverted Row (Bodyweight)', muscle: 'Back', category: 'Bodyweight', level: 'Intermediate', image: 'inverted_row' },
  { id: 50, name: 'Childs Pose (Post)', muscle: 'Back', category: 'Post_warmup', level: 'Beginner', image: 'childs_pose_post' },

  // HAMSTRINGS (51-60)
  { id: 51, name: 'Leg Swings', muscle: 'Hamstrings', category: 'Pre_warmup', level: 'Beginner', image: 'leg_swings' },
  { id: 52, name: 'Standing Hamstring Stretch', muscle: 'Hamstrings', category: 'Pre_warmup', level: 'Beginner', image: 'standing_hamstring_stretch' },
  { id: 53, name: 'Romanian Deadlift (Barbell)', muscle: 'Hamstrings', category: 'Barbell', level: 'Intermediate', image: 'barbell_romanian_deadlift' },
  { id: 54, name: 'Romanian Deadlift (Dumbbell)', muscle: 'Hamstrings', category: 'Dumbbell', level: 'Intermediate', image: 'dumbbell_romanian_deadlift' },
  { id: 55, name: 'Machine Leg Curl', muscle: 'Hamstrings', category: 'Machine', level: 'Beginner', image: 'machine_leg_curl' },
  { id: 56, name: 'Cable Pull-Through (Hamstrings)', muscle: 'Hamstrings', category: 'Cable', level: 'Intermediate', image: 'cable_pull_through_hamstrings' },
  { id: 57, name: 'Good Morning (Barbell)', muscle: 'Hamstrings', category: 'Barbell', level: 'Advanced', image: 'barbell_good_morning' },
  { id: 58, name: 'Bodyweight Hip Hinge', muscle: 'Hamstrings', category: 'Bodyweight', level: 'Beginner', image: 'bodyweight_hip_hinge' },
  { id: 59, name: 'Stability Ball Leg Curl', muscle: 'Hamstrings', category: 'Equipment', level: 'Intermediate', image: 'stability_ball_leg_curl' },
  { id: 60, name: 'Forward Fold (Post)', muscle: 'Hamstrings', category: 'Post_warmup', level: 'Beginner', image: 'forward_fold_post' },

  // BICEPS (61-70)
  { id: 61, name: 'Wrist Rotations', muscle: 'Biceps', category: 'Pre_warmup', level: 'Beginner', image: 'wrist_rotations' },
  { id: 62, name: 'Arm Shakeout', muscle: 'Biceps', category: 'Pre_warmup', level: 'Beginner', image: 'arm_shakeout' },
  { id: 63, name: 'Bicep Curl (Barbell)', muscle: 'Biceps', category: 'Barbell', level: 'Intermediate', image: 'barbell_bicep_curl' },
  { id: 64, name: 'Bicep Curl (Dumbbell)', muscle: 'Biceps', category: 'Dumbbell', level: 'Beginner', image: 'dumbbell_bicep_curl' },
  { id: 65, name: 'Cable Bicep Curl', muscle: 'Biceps', category: 'Cable', level: 'Intermediate', image: 'cable_bicep_curl' },
  { id: 66, name: 'Machine Preacher Curl', muscle: 'Biceps', category: 'Machine', level: 'Beginner', image: 'machine_preacher_curl' },
  { id: 67, name: 'Hammer Curl (Dumbbell)', muscle: 'Biceps', category: 'Dumbbell', level: 'Intermediate', image: 'dumbbell_hammer_curl' },
  { id: 68, name: 'Concentration Curl (Dumbbell)', muscle: 'Biceps', category: 'Dumbbell', level: 'Intermediate', image: 'dumbbell_concentration_curl' },
  { id: 69, name: 'EZ Bar Curl', muscle: 'Biceps', category: 'Barbell', level: 'Intermediate', image: 'ez_bar_curl' },
  { id: 70, name: 'Cross-Body Hammer Curl (Post)', muscle: 'Biceps', category: 'Post_warmup', level: 'Intermediate', image: 'cross_body_hammer_curl_post' },

  // TRICEPS (71-80)
  { id: 71, name: 'Tricep Stretch (Pre)', muscle: 'Triceps', category: 'Pre_warmup', level: 'Beginner', image: 'tricep_stretch_pre' },
  { id: 72, name: 'Arm Overhead Extension (No Weight)', muscle: 'Triceps', category: 'Pre_warmup', level: 'Beginner', image: 'arm_overhead_extension_no_weight' },
  { id: 73, name: 'Skull Crushers (Barbell)', muscle: 'Triceps', category: 'Barbell', level: 'Intermediate', image: 'barbell_skull_crushers' },
  { id: 74, name: 'Overhead Tricep Extension (Dumbbell)', muscle: 'Triceps', category: 'Dumbbell', level: 'Intermediate', image: 'dumbbell_overhead_tricep_extension' },
  { id: 75, name: 'Cable Tricep Pushdown', muscle: 'Triceps', category: 'Cable', level: 'Intermediate', image: 'cable_tricep_pushdown' },
  { id: 76, name: 'Machine Tricep Extension', muscle: 'Triceps', category: 'Machine', level: 'Beginner', image: 'machine_tricep_extension' },
  { id: 77, name: 'Close-Grip Bench Press (Barbell)', muscle: 'Triceps', category: 'Barbell', level: 'Advanced', image: 'barbell_close_grip_bench_press' },
  { id: 78, name: 'Bench Dip (Bodyweight)', muscle: 'Triceps', category: 'Bodyweight', level: 'Intermediate', image: 'bench_dip' },
  { id: 79, name: 'Kickbacks (Dumbbell)', muscle: 'Triceps', category: 'Dumbbell', level: 'Intermediate', image: 'dumbbell_kickbacks' },
  { id: 80, name: 'Overhead Tricep Stretch (Post)', muscle: 'Triceps', category: 'Post_warmup', level: 'Beginner', image: 'overhead_tricep_stretch_post' },

  // EXTRA EXERCISES (81-100)
  { id: 81, name: 'Farmer’s Walk (Dumbbell)', muscle: 'Back', category: 'Dumbbell', level: 'Intermediate', image: 'dumbbell_farmers_walk' },
  { id: 82, name: 'Farmer’s Walk (Barbell)', muscle: 'Back', category: 'Barbell', level: 'Intermediate', image: 'barbell_farmers_walk' },
  { id: 83, name: 'Burpees', muscle: 'Core', category: 'Bodyweight', level: 'Intermediate', image: 'burpees' },
  { id: 84, name: 'Hollow Hold', muscle: 'Core', category: 'Bodyweight', level: 'Intermediate', image: 'hollow_hold' },
  { id: 85, name: 'Upright Row (Barbell)', muscle: 'Shoulders', category: 'Barbell', level: 'Intermediate', image: 'barbell_upright_row' },
  { id: 86, name: 'Shrug (Dumbbell)', muscle: 'Shoulders', category: 'Dumbbell', level: 'Intermediate', image: 'dumbbell_shrug' },
  { id: 87, name: 'Fly (Dumbbell)', muscle: 'Chest', category: 'Dumbbell', level: 'Intermediate', image: 'dumbbell_fly' },
  { id: 88, name: 'Neck Press (Barbell)', muscle: 'Chest', category: 'Barbell', level: 'Intermediate', image: 'barbell_neck_press' },
  { id: 89, name: 'Pistol Squat', muscle: 'Legs', category: 'Bodyweight', level: 'Advanced', image: 'pistol_squat' },
  { id: 90, name: 'Split Squat (Dumbbell)', muscle: 'Legs', category: 'Dumbbell', level: 'Intermediate', image: 'dumbbell_split_squat' },
  { id: 91, name: 'Bent Over Reverse Fly (Dumbbell)', muscle: 'Shoulders', category: 'Dumbbell', level: 'Intermediate', image: 'dumbbell_bent_over_reverse_fly' },
  { id: 92, name: 'Pendlay Row (Barbell)', muscle: 'Back', category: 'Barbell', level: 'Intermediate', image: 'barbell_pendlay_row' },
  { id: 93, name: 'Hyperextension (Machine)', muscle: 'Back', category: 'Machine', level: 'Intermediate', image: 'machine_hyperextension' },
  { id: 94, name: 'Glute-Ham Raise (Machine)', muscle: 'Hamstrings', category: 'Machine', level: 'Intermediate', image: 'machine_glute_ham_raise' },
  { id: 95, name: 'Spider Curl (Dumbbell)', muscle: 'Biceps', category: 'Dumbbell', level: 'Intermediate', image: 'dumbbell_spider_curl' },
  { id: 96, name: '21s (Barbell Curl)', muscle: 'Biceps', category: 'Barbell', level: 'Advanced', image: 'barbell_21s' },
  { id: 97, name: 'Diamond Push-ups', muscle: 'Triceps', category: 'Bodyweight', level: 'Intermediate', image: 'diamond_push_ups' },
  { id: 98, name: 'Reverse Grip Tricep Pushdown (Cable)', muscle: 'Triceps', category: 'Cable', level: 'Intermediate', image: 'cable_reverse_grip_tricep_pushdown' },
  { id: 99, name: 'Donkey Kicks (Legs)', muscle: 'Legs', category: 'Bodyweight', level: 'Beginner', image: 'donkey_kicks' },
  { id: 100, name: 'Seated Calf Raise (Machine)', muscle: 'Legs', category: 'Machine', level: 'Beginner', image: 'machine_seated_calf_raise' }
];

export const bodyParts = [
  'Core',
  'Shoulders',
  'Chest',
  'Legs',
  'Back',
  'Hamstrings',
  'Biceps',
  'Triceps',
  'Abs'
];

export const categories = [
  'Barbell',
  'Dumbbell',
  'Cable',
  'Machine',
  'Equipment',
  'Bodyweight',
];
